# Backup build verification workflow
name: Build Verification

on:
  push:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install and build
        run: |
          npm run install-all
          cd client && npm run build
          
      - name: Success
        run: echo "✅ ATLASE ROI application builds successfully!"
