name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm run install-all

    - name: Build React app
      run: |
        cd client
        npm run build

    - name: Verify build
      run: |
        echo "✅ Build completed successfully!"
        ls -la client/build/
